// TypeScript Types
var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 3 * 3;
myBool = false;
myVar = true;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3, 4, 5,];
boolArr = [true, false, false, true];
strNumTuple = ['Hi', 7, false];
console.log(strNumTuple);
